[tool.ruff]
target-version = "py38"
select = [
  "B",   # flake8-bugbear
  "D",   # pydocstyle
  "E",   # pycodestyle
  "ERA", # flake8-eradicate
  "F",   # pyflakes
  "I",   # isort
  "PLE", # pylint error
  "PLW", # pylint warning
  "PYI", # flakes8-pyi
  "Q",   # flake8-quotes
  "SIM", # flake8-simplify
  "TID", # tidy imports
  "UP",  # pyupgrade
  "W",   # pycodestyle
  "YTT", # flake8-2020
]
ignore = [
  "B019",    # functools.lru_cache on methods can lead to memory leaks
  "B023",    # Function definition does not bind loop variable
  "B904",    # Within an except clause, raise exceptions with ...
  "D100",    # Missing docstring in public module
  "D104",    # Missing docstring in public package
  "D205",    # 1 blank line required between summary line and description
  "E741",    # tmp: we should fix all ambiguous variable names
  "PLR2004", # Magic number
  "PLW0120", # tmp: awaiting bug fix https://github.com/charliermarsh/ruff/issues/3019
]
pydocstyle.convention = "google"

[tool.ruff.per-file-ignores]
"tests/*" = ["D103"]
"examples/*" = ["D102", "D103", "D107", "E402"]
