name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['**/*.py', '.github/workflows/ci.yml']
  pull_request:
    branches: [main]
    paths: ['**/*.py', '.github/workflows/ci.yml']

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        # [test]: see options.extras_require in setup.cfg
        run: pip install .[test]

      - name: Run tests
        run: pytest --durations 0
